# Generated by Django 6.0 on 2026-03-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
