# Generated by Django 6.0 on 2026-04-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255)),
                ('product_tag', models.CharField(max_length=255)),
                ('product_desc', models.TextField()),
                ('product_img', models.ImageField(upload_to='portfolio/')),
            ],
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
