# Generated by Django 6.0 on 2026-04-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0004_portfolio_alter_sitesetting_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=200)),
                ('about_img', models.ImageField(upload_to='about_images/')),
                ('about_heading', models.CharField(max_length=200)),
                ('about_subheading', models.TextField()),
            ],
        ),
    ]
