# Generated by Django 6.0 on 2026-04-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0005_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_tag',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
